name: Feat - 기능 추가
description: 새로운 기능 개발
title: "[Feat] "
type: Feat
body:
  - type: textarea
    attributes:
      label: 배경 및 목적
      placeholder: 기능의 필요와 목적을 설명해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 기능 명세
      placeholder: 기능의 상세 동작 내용을 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 성공 기준
      placeholder: 기능이 성공적으로 구현되었음을 판단할 기준을 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 목록
      placeholder: |
        - [ ] A 구현
        - [ ] B 구현
