name: Fix - 버그 수정
description: 버그 상황을 재현하고 수정
title: "[Fix] "
type: Fix
body:
  - type: textarea
    attributes:
      label: 발생 환경
      placeholder: 버그가 발생한 환경(운영체제, 브라우저 등)을 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 재현 단계
      placeholder: 버그를 재현하기 위한 구체적인 단계를 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 버그 발생시 결과
      placeholder: 버그가 발생했을 때의 구체적인 결과를 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 예상 결과
      placeholder: 버그가 없을 때 기대되는 정상적인 결과를 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 목록
      placeholder: |
        - [ ] A 구현
        - [ ] B 구현
