name: Ref - 리팩토링
description: 코드 스타일, 이름변경, 구조 변경 등 기능 변경이 없는 코드작업
title: "[Ref] "
type: Ref
body:
  - type: textarea
    attributes:
      label: 배경 및 목적
      placeholder: 작업의 필요와 목적을 설명해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 목록
      placeholder: |
        - [ ] A 구현
        - [ ] B 구현
