name: Test - 테스트
description: 기능, 시스템의 테스트 작업
title: "[Test] "
type: Test
body:
  - type: textarea
    attributes:
      label: 테스트 대상
      placeholder: 테스트 대상(기능, 시스템 등)을 설명해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 테스트 방법 및 로직
      placeholder: 테스트를 수행할 방법과 로직을 기술해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 목록
      placeholder: |
        - [ ] A 구현
        - [ ] B 구현
